spring.application.name=SecureBankingBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/securebanking
spring.datasource.username=postgres
spring.datasource.password=manav@17

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
